import type { Metadata } from "next";
import "./globals.css";
import { Box, ChakraProvider } from "@chakra-ui/react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Box className="box" w="100%" minH="100vh" h='auto'>
          {children}
          </Box>
        </ChakraProvider>
      </body>
    </html>
  );
}
